services:
  nginx:
    build: ./nginx
    container_name: taskforge-nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - taskforge-net
  api:
    build: ./api
    container_name: taskforge-api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tasks_db
    depends_on:
      - db
    networks:
      - taskforge-net
    restart: always
    healthcheck:
      test: ["CMD" , "node" , "--spider" ,"-q","http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
  db:
    image: mysql:latest
    container_name: taskforge-db
    environment: 
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: tasks_db
    networks:
      - taskforge-net
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
networks:
  taskforge-net:
